// ---------------------------------------------------------
// Delphi — Inshorts-style brief cards
// Data is embedded directly (rather than fetched) so the page
// works when opened straight from disk in Chrome/Edge, with no
// local server required.
// ---------------------------------------------------------

const DUMMY_IMAGE = "assets/shl-logo.png";
const DUMMY_URL = "https://www.shl.com/careers/";

const RAW_STORIES = [
  { title: "OpenAI and Hugging Face address security incident during model evaluation", description: "OpenAI and Hugging Face jointly disclosed and remediated a security incident discovered during a routine model evaluation process." },
  { title: "Kimi K3 Is Competitive with Fable; Kimi K3 and Fable Is SoTA", description: "New benchmark results show Kimi K3 matching Fable's performance, with both models setting state-of-the-art scores." },
  { title: "Introduction to Formal Verification with Lean Part 1", description: "The first part of a series introducing formal verification concepts using the Lean theorem prover." },
  { title: "Intel Starts Shipping High-NA EUV Silicon", description: "Intel has begun shipping its first chips manufactured using High-NA EUV lithography technology." },
  { title: "Original Apollo 11 Guidance Computer source code for command and lunar modules", description: "The original assembly source code for the Apollo 11 command and lunar module guidance computers, preserved on GitHub." },
  { title: "Advertise in ChatGPT", description: "OpenAI opens up an advertising platform allowing brands to place ads within ChatGPT conversations." },
  { title: "FreeInk: Open ecosystem for e-readers", description: "A new open-source ecosystem aiming to bring open standards and freedom to e-reader devices." },
  { title: "Late.sh – a command-line Clubhouse for computer people", description: "A terminal-based social audio app inspired by Clubhouse, built for developers and command-line enthusiasts." },
  { title: "Judge approves $1.5B Anthropic settlement for pirated books used to train Claude", description: "A federal judge has approved a $1.5 billion settlement in the case over pirated books used to train Anthropic's Claude models." },
  { title: "Gemini 3.6 Flash, 3.5 Flash-Lite, and 3.5 Flash Cyber", description: "Google announces new Gemini Flash model variants focused on speed and cost efficiency." },
  { title: "A digestion of the Jacobian conjecture counterexample", description: "A detailed breakdown and analysis of a proposed counterexample to the Jacobian conjecture." },
  { title: "Codeberg: ToU extension to prohibit LLM-extrusions", description: "Codeberg updates its Terms of Use to explicitly prohibit content generated by extracting or scraping via LLMs." },
  { title: "Show HN: A new kind of FPS aim trainer", description: "A Show HN submission introducing a novel approach to first-person-shooter aim training tools." },
  { title: "Ten Steps Towards Happiness (2015)", description: "A 2015 essay outlining ten practical steps for achieving greater personal happiness." },
];

const STORIES = RAW_STORIES.map((s) => ({
  ...s,
  imageURL: DUMMY_IMAGE,
  readmoreURL: DUMMY_URL,
}));

const THUMB_SVG = `<svg viewBox="0 0 24 24" fill="none">
  <path d="M8 21H5a1 1 0 0 1-1-1v-9a1 1 0 0 1 1-1h3m0 11V10m0 11h9.28a2 2 0 0 0 1.98-1.7l1.25-8A2 2 0 0 0 18.53 9H14V4.5A1.5 1.5 0 0 0 12.5 3c-.4 0-.78.2-1 .53L8 10"
    stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/>
</svg>`;

const FEEDBACK_KEY = "delphi-feedback-v1";

function loadFeedback() {
  try {
    return JSON.parse(localStorage.getItem(FEEDBACK_KEY)) || {};
  } catch (e) {
    return {};
  }
}

function saveFeedback() {
  try {
    localStorage.setItem(FEEDBACK_KEY, JSON.stringify(feedback));
  } catch (e) {
    // storage unavailable (e.g. private mode) — feedback just won't persist
  }
}

const feedback = loadFeedback();

function toggleFeedback(index, value, upBtn, downBtn) {
  feedback[index] = feedback[index] === value ? undefined : value;
  if (feedback[index] === undefined) delete feedback[index];
  saveFeedback();

  upBtn.classList.toggle("active", feedback[index] === "up");
  upBtn.setAttribute("aria-pressed", String(feedback[index] === "up"));
  downBtn.classList.toggle("active", feedback[index] === "down");
  downBtn.setAttribute("aria-pressed", String(feedback[index] === "down"));
}

// ---------------------------------------------------------

const cardViewport = document.getElementById("cardViewport");
const progressTrack = document.getElementById("progressTrack");
const nextBtn = document.getElementById("nextBtn");
const viewToggle = document.getElementById("viewToggle");
const body = document.body;

let currentIndex = 0;
let isAnimating = false;
const ANIM_MS = 420;

function isLogoImage(url) {
  return url.includes("shl-logo.png");
}

function buildCard(index) {
  const story = STORIES[index];
  const card = document.createElement("div");
  card.className = "card";

  const media = document.createElement("div");
  media.className = "card-media" + (isLogoImage(story.imageURL) ? " logo-image" : "");

  const img = document.createElement("img");
  img.src = story.imageURL;
  img.alt = story.title;
  media.appendChild(img);

  const tag = document.createElement("span");
  tag.className = "card-tag";
  tag.textContent = "SHL Careers";
  media.appendChild(tag);

  const count = document.createElement("span");
  count.className = "card-count";
  count.textContent = `${index + 1} / ${STORIES.length}`;
  media.appendChild(count);

  const bodyEl = document.createElement("div");
  bodyEl.className = "card-body";

  const title = document.createElement("h2");
  title.className = "card-title";
  title.textContent = story.title;

  const desc = document.createElement("p");
  desc.className = "card-desc";
  desc.textContent = story.description;

  const footer = document.createElement("div");
  footer.className = "card-footer";

  const source = document.createElement("span");
  source.className = "source-tag";
  source.textContent = "shl.com";

  const link = document.createElement("a");
  link.className = "read-more";
  link.href = story.readmoreURL;
  link.target = "_blank";
  link.rel = "noopener noreferrer";
  link.innerHTML = `Read more
    <svg viewBox="0 0 24 24" fill="none">
      <path d="M7 17L17 7M17 7H9M17 7V15" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>`;

  const reactions = document.createElement("div");
  reactions.className = "reaction-group";

  const upBtn = document.createElement("button");
  upBtn.type = "button";
  upBtn.className = "reaction-btn up" + (feedback[index] === "up" ? " active" : "");
  upBtn.setAttribute("aria-label", "Thumbs up");
  upBtn.setAttribute("aria-pressed", String(feedback[index] === "up"));
  upBtn.innerHTML = THUMB_SVG;

  const downBtn = document.createElement("button");
  downBtn.type = "button";
  downBtn.className = "reaction-btn down thumb-down" + (feedback[index] === "down" ? " active" : "");
  downBtn.setAttribute("aria-label", "Thumbs down");
  downBtn.setAttribute("aria-pressed", String(feedback[index] === "down"));
  downBtn.innerHTML = THUMB_SVG;

  upBtn.addEventListener("click", () => toggleFeedback(index, "up", upBtn, downBtn));
  downBtn.addEventListener("click", () => toggleFeedback(index, "down", upBtn, downBtn));

  reactions.appendChild(upBtn);
  reactions.appendChild(downBtn);

  const actions = document.createElement("div");
  actions.className = "footer-actions";
  actions.appendChild(reactions);
  actions.appendChild(link);

  footer.appendChild(source);
  footer.appendChild(actions);

  bodyEl.appendChild(title);
  bodyEl.appendChild(desc);
  bodyEl.appendChild(footer);

  card.appendChild(media);
  card.appendChild(bodyEl);

  return card;
}

function renderProgress() {
  progressTrack.innerHTML = "";
  STORIES.forEach((_, i) => {
    const seg = document.createElement("div");
    seg.className = "progress-seg" + (i <= currentIndex ? " filled" : "");
    const fill = document.createElement("div");
    fill.className = "fill";
    seg.appendChild(fill);
    progressTrack.appendChild(seg);
  });
}

function initCards() {
  cardViewport.innerHTML = "";
  const card = buildCard(currentIndex);
  cardViewport.appendChild(card);
  renderProgress();
}

function goTo(nextIndex, direction) {
  // direction: "next" -> new card enters from bottom, old exits top
  //            "prev" -> new card enters from top, old exits bottom
  if (isAnimating) return;
  isAnimating = true;

  const outgoing = cardViewport.querySelector(".card");
  const incoming = buildCard(nextIndex);

  incoming.classList.add(direction === "next" ? "entering-from-bottom" : "entering-from-top");
  cardViewport.appendChild(incoming);

  // force reflow so the entering class transition applies
  void incoming.offsetWidth;

  outgoing.classList.add(direction === "next" ? "leaving-to-top" : "leaving-to-bottom");
  incoming.classList.remove("entering-from-bottom", "entering-from-top");

  currentIndex = nextIndex;
  renderProgress();

  setTimeout(() => {
    outgoing.remove();
    isAnimating = false;
  }, ANIM_MS);
}

function next() {
  const nextIndex = (currentIndex + 1) % STORIES.length;
  goTo(nextIndex, "next");
}

function prev() {
  const prevIndex = (currentIndex - 1 + STORIES.length) % STORIES.length;
  goTo(prevIndex, "prev");
}

// ---------------- Controls ----------------

nextBtn.addEventListener("click", next);

document.addEventListener("keydown", (e) => {
  if (["ArrowDown", "PageDown", " "].includes(e.key)) {
    e.preventDefault();
    next();
  } else if (["ArrowUp", "PageUp"].includes(e.key)) {
    e.preventDefault();
    prev();
  }
});

let wheelCooldown = false;
cardViewport.addEventListener(
  "wheel",
  (e) => {
    if (wheelCooldown) return;
    if (Math.abs(e.deltaY) < 12) return;
    wheelCooldown = true;
    if (e.deltaY > 0) next();
    else prev();
    setTimeout(() => (wheelCooldown = false), ANIM_MS + 80);
  },
  { passive: true }
);

let touchStartY = null;
cardViewport.addEventListener(
  "touchstart",
  (e) => {
    touchStartY = e.touches[0].clientY;
  },
  { passive: true }
);

cardViewport.addEventListener(
  "touchend",
  (e) => {
    if (touchStartY === null) return;
    const deltaY = touchStartY - e.changedTouches[0].clientY;
    if (Math.abs(deltaY) > 60) {
      if (deltaY > 0) next();
      else prev();
    }
    touchStartY = null;
  },
  { passive: true }
);

// ---------------- View toggle (Web / Mobile) ----------------

viewToggle.addEventListener("click", (e) => {
  const btn = e.target.closest(".toggle-option");
  if (!btn) return;
  const mode = btn.dataset.mode;

  viewToggle.dataset.active = mode;
  viewToggle.querySelectorAll(".toggle-option").forEach((opt) => {
    opt.setAttribute("aria-pressed", opt.dataset.mode === mode ? "true" : "false");
  });

  body.classList.toggle("mode-mobile", mode === "mobile");
  body.classList.toggle("mode-web", mode === "web");
});

// ---------------- Init ----------------

initCards();
